CSVCategoryList/Models/CategoryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CSVCategoryList.Models
{
    public class CategoryModel
    {
        public int ID { get; set; }

        //Cat Name  
        public string Name { get; set; }

        //represnts Parent ID and it's nullable  
        public int? Pid { get; set; }

    }

    public class CategoryTree
    {
        public List<CategoryTree> Children = new List<CategoryTree>();
        public CategoryTree Parent { get; set; }
        public CategoryModel Data { get; set; }


        public List<CategoryTree> BuildTreeAndGetRoots(List<CategoryModel> actualObjects)
        {
            var lookup = new Dictionary<int, CategoryTree>();
            var rootNodes = new List<CategoryTree>();

            foreach (var item in actualObjects)
            {
                // add us to lookup
                CategoryTree ourNode;
                if (lookup.TryGetValue(item.ID, out ourNode))
                {   // was already found as a parent - register the actual object
                    ourNode.Data = item;
                }
                else
                {
                    ourNode = new CategoryTree() { Data = item };
                    lookup.Add(item.ID, ourNode);
                }

                
                if (item.Pid == null)
                {   // is a root node
                    rootNodes.Add(ourNode);
                }
                else
                {   // is a child row - so we have a parent
                    CategoryTree parentNode;
                    if (!lookup.TryGetValue((int)item.Pid, out parentNode))
                    {   // unknown parent, construct preliminary parent
                        parentNode = new CategoryTree();
                        lookup.Add((int)item.Pid, parentNode);
                    }

                    parentNode.Children.Add(ourNode);
                    ourNode.Parent = parentNode;
                }
            }

            return rootNodes;
        }
    }


}

CSVCategoryList/Models/FileUploadModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CSVCategoryList.Models
{
    public class FileUploadModel
    {
        [DataType(DataType.Upload)]
        [Display(Name = "Upload File")]
        [Required(ErrorMessage = "Please choose file to upload.")]
        public string file { get; set; }
    }
}

CSVCategoryList/Controllers/FileUploadController.cs
using CSVCategoryList.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace CSVCategoryList.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: FileUpload
        public ActionResult UploadForm()
        {
            return View();
        }

        [HttpPost]
        public JsonResult UploadFile()
        {

            string Message, fileName, actualFileName;

            Message = fileName = actualFileName = string.Empty;

            bool flag = false;

            List<CategoryModel> categories = new List<CategoryModel>();
            List<CategoryTree> tree =new List<CategoryTree>();



            if (Request.Files != null)
            {
                var file = Request.Files[0];
                actualFileName = file.FileName;
                fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                int size = file.ContentLength;

                try
                {
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);
                    file.SaveAs(path);

                    string csvData = System.IO.File.ReadAllText(path);

                    //Execute a loop over the rows.
                    foreach (string row in csvData.Split('\n'))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            var csvRow = row.Split(',');

                            CategoryModel c = new CategoryModel();

                            c.ID = Int32.Parse(csvRow[0]);
                            c.Pid = csvRow[1] != "" ? (int?)Int32.Parse(csvRow[1]) : null;
                            c.Name = csvRow[2];

                            categories.Add(c);

                        }
                     
                    }
                    // Build category tree list 
                    tree = new CategoryTree().BuildTreeAndGetRoots(categories.OrderBy(c => c.Pid).ToList());
                   
                }
                catch (Exception)
                {
                    Message = "File upload failed! Please try again";
                }
               
            }
           
            return new JsonResult
            {
                Data = new
                {
                    Message = Message,
                    FileName = fileName,
                    Status = flag,
                    categories = JsonConvert.SerializeObject(tree,Formatting.None,
                    new JsonSerializerSettings() {
                        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
                    }) 
                }
            };

        
        }

    }
}

CSVCategoryList/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CSVCategoryList.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
      
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CSVCategoryList/Views/FileUpload/CategoryList.cshtml
@using CSVCategoryList.Models
@model List<CategoryModel>

@*Razor solution for displaying category tree  *@
@{
    ViewBag.Title = "CategoryList";
}

<h2>Category list</h2>

<p>
    @Html.ActionLink("Back to upload", "Index")
</p>
@if (Model != null)
{
    @DisplayTree(Model.Where(e => e.Pid == null).OrderBy(e => e.ID));
}




@helper DisplayTree(IEnumerable<CSVCategoryList.Models.CategoryModel> elements)
{
        <ul>
            @foreach (var element in elements)
            {
                <li>
                    @element.Name
                    @{
                        var children = Model.Where(e => e.Pid == element.ID).OrderBy(e => e.ID);
                        if (children.Count() > 0)
                        {
                            @DisplayTree(children.ToList())
                        }
                    }
                </li>
            }
        </ul>
}

CSVCategoryList/Views/FileUpload/Index1.cshtml
@model CSVCategoryList.Models.FileUploadModel

@{
    ViewBag.Title = "Upload CSV file";
}

<h2>Upload CSV file</h2>

@* Razor solution for upload form *@
@using (Html.BeginForm("UploadFiles", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.file, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-primary" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.FileStatus
            </div>
        </div>
    </div>

}
@section Scripts {
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

CSVCategoryList/Views/FileUpload/UploadForm.cshtml
@{
    ViewBag.Title = "Upload";
}

<h2>Upload file</h2>
<div ng-app="CsvApp" ng-controller="UploadController">
    <div class="grid">
        <div class="row">
            <form novalidate name="uploadForm" ng-submit="SaveFile()" class="float-left">
                <div style="color: red">{{Message}}</div>
                <div class="form-group">
                    <label for="file" class="col-md-2 control-label">Select File :</label>
                    <div class="col-md-10">
                        <input type="file" name="file" accept=".csv" onchange="angular.element(this).scope().selectFileforUpload(this.files)" required />
                        <span class="error">{{FileInvalidMessage}}</span>
                        <span class="error" ng-show="(uploadForm.file.$dirty || IsFormSubmitted) && uploadForm.file.$error.required">File required!</span>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2 top-offset-15">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div class="row top-offset-15">
            <script type="text/ng-template" id="nodes_renderer">
                <div ui-tree-handle>
                    {{node.Data.Name}}
                </div>
                <ul ui-tree-nodes="" ng-model="node.Children">
                    <li ng-repeat="node in node.Children" ui-tree-node ng-include="'nodes_renderer'">
                    </li>
                </ul>
            </script>
            <div ui-tree ng-show="showCategories">
                <ul ui-tree-nodes="" ng-model="categories" id="tree-root">
                    <li ng-repeat="node in categories" ui-tree-node ng-include="'nodes_renderer'"></li>
                </ul>
            </div>
        </div>
    </div>
</div>




@section Scripts{
    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/angular-ui-tree.js"></script>
    <script src="~/AngularJs/js/App.js"></script>
    <script src="~/AngularJs/js/UploadController.js"></script>

}

CSVCategoryList/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CSVCategoryList/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CSVCategoryList/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CSVCategoryList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link href="~/AngularJs/css/App.css" rel="stylesheet" type="text/css" />
    <link href="~/AngularJs/css/angular-ui-tree.min.css"  rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CSVCategoryList", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Upload", "UploadForm", "FileUpload")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
   
    @RenderSection("scripts", required: false)
</body>
</html>